permalink: /:year/:title
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'fenced_code_blocks', 'strikethrough', 'autolink',
  'no_intra_emphasis']

exclude:
  - Gemfile
  - Gemfile.lock
  - bower.json
  - bower_components
  - sass
  - node_modules
  - Gruntfile.js
  - css
  - Rakefile
  - README.md
  - package.json

production_url : http://jeduan.com # or your custom domain name
title : Jeduan

author :
  name : Jeduan Cornejo
  email : jeduan@gmail.com
  github : jeduan
  twitter : jeduan
