permalink: /:year/:title
highlighter: pygments
var:
  archive_path: /archive.html
  categories_path : /categories.html

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - bower.json
  - bower_components
  - sass
  - node_modules
  - Gruntfile.js
  - css
  - Rakefile
  - README.md
  - package.json

production_url : http://www.]jeduan.com
title : Jeduan

author :
  name : Jeduan Cornejo
  email : jeduan@gmail.com
  github : jeduan
  twitter : jeduan
